
# This is a basic workflow to help you get started with Actions

name: Fourth MARKETPLACE

on:
    push:
        branches: [ "main" ]

jobs:
    ubuntu:
        runs-on: ubuntu-latest
        steps:
            - name DockerImage
            uses: docker://python3:latest


