# This is a basic workflow to help you get started with Actions

name: SECOND

on:
    push:
        branches: [ "main" ]

jobs:
    job1:
        name: first-job
        runs-on: ubuntu-latest
        steps:
            - name: step1
              uses: actions/checkout@v4 
            - name: step2
              run: env | sort
    job2:
        name: second-job
        runs-on: windows-latest
        steps:
            - name: step1
              uses: actions/checkout@v4
            - name: step2
              run: "Get-ChildItem Env: | Sort-Object Name"