name: second

on: push

jobs:
    job1:
        name: first-job
        uses: ubuntu-latest
        steps:
            - name: step1
              uses: actions/checkout@v4
            
            
            - name: step2
              run: env | sort
    job2:
        name: second-job
        uses: windows-latest
        steps:
            - name: step1
              uses: actions/checkout@v4
            - name: step2
              run: "Get-ChildItem Env: | Sort-Object Name"
