
# This is a basic workflow to help you get started with Actions

name: SIXTH PYTHON

on:
    push:
        branches: [ "main" ]

jobs:
    first:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: python script.py
    second:
        needs: [first]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/upload-artifact@v4
              with:
                name: hello
                path: .
        