
# This is a basic workflow to help you get started with Actions

name: THIRD

on:
    push:
        branches: [ "main" ]

jobs:
    ubuntu:
        runs-on: ubuntu-latest
        steps:
        - run: date
    windows:
        runs-on: windows-latest
        steps:
            - run: date
    macos:
        runs-on: macos-latest
        steps:
            - run: date
    depends:
        runs-on: ubuntu-latest
        needs: [ubuntu, windows, macos]
        steps:
            - run: date
